services:
    db:
        image: postgres
        container_name: postgres
        user: postgres
        volumes:
            - pg_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        healthcheck:
            test: [ "CMD", "pg_isready" ]
            interval: 10s
            timeout: 5s
            retries: 5

    scraper:
        image: selenium/standalone-chrome:131.0.6778.108-chromedriver-131.0.6778.87-grid-4.27.0-20241204
        container_name: scraper
        ports:
            - '4444:4444'

    backend:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: concertify_backend
        ports:
            - "5000:80"
            - "5001:443"

        volumes: 
            - app_data:/app
        env_file:
            - ./src/Concertify.API/TestEnv.env
        depends_on: 
            db:
                condition: service_healthy
                restart: true

volumes:
    pg_data:
    app_data:

