services:
    db:
        image: postgres
        container_name: postgres
        user: postgres
        volumes:
            - pg_data:/var/lib/postgresql/data
        env_file:
            - ./src/Concertify.API/TestEnv.env
        ports:
            - '5432:5432'
        healthcheck:
            test: [ "CMD", "pg_isready" ]
            interval: 10s
            timeout: 5s
            retries: 5

    backend:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: concertify_backend
        ports:
            - "5213:80"
            - 443
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
        volumes: 
            - app_data:/app
        env_file:
            - ./src/Concertify.API/TestEnv.env
        depends_on: 
            db:
                condition: service_healthy
                restart: true

volumes:
    pg_data:
    app_data:

