services:
    db:
        image: postgres
        container_name: postgres
        user: postgres
        volumes:
            - pg_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        healthcheck:
            test: [ "CMD", "pg_isready" ]
            interval: 10s
            timeout: 5s
            retries: 5

    backend:
        build:
            context: .
            dockerfile: ./Dockerfile
            target: final
        container_name: concertify_backend
        ports:
            - "5000:80"
            - "5001:443"

        volumes: 
            - app_data:/app
        depends_on: 
            db:
                condition: service_healthy
                restart: true
        develop:
            watch:
                - action: rebuild
                  path: .


volumes:
    pg_data:
    app_data:

